"""Monte Carlo permutation test for positional bias significance.

Tests whether the observed positional bias (first_ratio, last_ratio) of a sign
is statistically significant against the null hypothesis of random positioning.
The null is generated by randomly permuting the positions of all tokens within
each inscription (preserving inscription length), then recomputing the metric.

Output: p-values and effect sizes for each sign.
"""

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

from spectral_submersion.tokenization import get_sequences_by_line


def compute_positional_metrics(
    sequences: list[list[str]], min_count: int = 5
) -> pd.DataFrame:
    """Compute first_ratio and last_ratio for each sign."""
    stats = {}
    for seq in sequences:
        n = len(seq)
        if n == 0:
            continue
        for pos, tok in enumerate(seq):
            if tok not in stats:
                stats[tok] = {"count": 0, "first": 0, "last": 0}
            stats[tok]["count"] += 1
            if pos == 0:
                stats[tok]["first"] += 1
            elif pos == n - 1:
                stats[tok]["last"] += 1

    rows = []
    for tok, s in stats.items():
        if s["count"] < min_count:
            continue
        rows.append(
            {
                "token": tok,
                "count": s["count"],
                "first_ratio": s["first"] / s["count"],
                "last_ratio": s["last"] / s["count"],
            }
        )
    return pd.DataFrame(rows)


def permute_within_sequences(sequences: list[list[str]], seed: int) -> list[list[str]]:
    """Shuffle tokens within each inscription, preserving length."""
    rng = np.random.default_rng(seed)
    permuted = []
    for seq in sequences:
        perm = list(seq)
        rng.shuffle(perm)
        permuted.append(perm)
    return permuted


def monte_carlo_positional_test(
    sequences: list[list[str]],
    n_permutations: int = 1000,
    min_count: int = 5,
    random_seed: int = 42,
) -> pd.DataFrame:
    """Run Monte Carlo permutation test for positional bias."""
    observed = compute_positional_metrics(sequences, min_count)
    tokens = observed["token"].tolist()

    # Store null distributions
    null_first = {tok: [] for tok in tokens}
    null_last = {tok: [] for tok in tokens}

    for p in range(n_permutations):
        permuted = permute_within_sequences(sequences, random_seed + p)
        null_metrics = compute_positional_metrics(permuted, min_count)
        for _, row in null_metrics.iterrows():
            tok = row["token"]
            if tok in null_first:
                null_first[tok].append(row["first_ratio"])
                null_last[tok].append(row["last_ratio"])

    results = []
    for _, row in observed.iterrows():
        tok = row["token"]
        fr_obs = row["first_ratio"]
        lr_obs = row["last_ratio"]

        fr_null = np.array(null_first[tok])
        lr_null = np.array(null_last[tok])

        # Two-tailed p-value
        if len(fr_null) > 0:
            fr_p = 2 * min(np.mean(fr_null >= fr_obs), np.mean(fr_null <= fr_obs))
            fr_p = min(fr_p, 1.0)
            fr_effect = (fr_obs - np.mean(fr_null)) / (np.std(fr_null) + 1e-12)
        else:
            fr_p = np.nan
            fr_effect = np.nan

        if len(lr_null) > 0:
            lr_p = 2 * min(np.mean(lr_null >= lr_obs), np.mean(lr_null <= lr_obs))
            lr_p = min(lr_p, 1.0)
            lr_effect = (lr_obs - np.mean(lr_null)) / (np.std(lr_null) + 1e-12)
        else:
            lr_p = np.nan
            lr_effect = np.nan

        results.append(
            {
                "token": tok,
                "count": row["count"],
                "first_ratio_obs": fr_obs,
                "first_ratio_null_mean": (
                    np.mean(fr_null) if len(fr_null) > 0 else np.nan
                ),
                "first_ratio_pvalue": fr_p,
                "first_ratio_effect": fr_effect,
                "last_ratio_obs": lr_obs,
                "last_ratio_null_mean": (
                    np.mean(lr_null) if len(lr_null) > 0 else np.nan
                ),
                "last_ratio_pvalue": lr_p,
                "last_ratio_effect": lr_effect,
            }
        )

    return pd.DataFrame(results)


def main():
    parser = argparse.ArgumentParser(
        description="Monte Carlo permutation test for positional bias"
    )
    parser.add_argument(
        "--input", default="data/raw/lost_language/corpus_indus_real.csv"
    )
    parser.add_argument("--output", default="reports/tables/positional_monte_carlo.csv")
    parser.add_argument("--n-permutations", type=int, default=1000)
    parser.add_argument("--min-count", type=int, default=5)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    df = pd.read_csv(args.input)
    sequences = get_sequences_by_line(df)

    print(f"Running Monte Carlo test with {args.n_permutations} permutations...")
    results = monte_carlo_positional_test(
        sequences,
        n_permutations=args.n_permutations,
        min_count=args.min_count,
        random_seed=args.seed,
    )

    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    results.to_csv(args.output, index=False)
    print(f"Saved results to {args.output}")

    # Significant results
    sig_first = results[
        (results["first_ratio_pvalue"] < 0.05) & (results["first_ratio_effect"] > 2)
    ]
    sig_last = results[
        (results["last_ratio_pvalue"] < 0.05) & (results["last_ratio_effect"] > 2)
    ]

    print(f"\nSigns with significant START bias (p<0.05, effect>2): {len(sig_first)}")
    print(
        sig_first[
            [
                "token",
                "count",
                "first_ratio_obs",
                "first_ratio_null_mean",
                "first_ratio_pvalue",
                "first_ratio_effect",
            ]
        ]
        .head(10)
        .to_string(index=False)
    )

    print(f"\nSigns with significant END bias (p<0.05, effect>2): {len(sig_last)}")
    print(
        sig_last[
            [
                "token",
                "count",
                "last_ratio_obs",
                "last_ratio_null_mean",
                "last_ratio_pvalue",
                "last_ratio_effect",
            ]
        ]
        .head(10)
        .to_string(index=False)
    )


if __name__ == "__main__":
    main()
